"""second  migration

Revision ID: 499302dacf88
Revises: bc1fd5cf6d4e
Create Date: 2024-10-24 11:45:27.850952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499302dacf88'
down_revision = 'bc1fd5cf6d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('uses', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designs', schema=None) as batch_op:
        batch_op.drop_column('uses')
        batch_op.drop_column('sales')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
