"""forth migration

Revision ID: 9c7d520eb23e
Revises: f00a5f84c2eb
Create Date: 2024-10-25 16:45:18.287444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7d520eb23e'
down_revision = 'f00a5f84c2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url_2', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_url_2')
        batch_op.drop_column('image_url_1')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
